const allCommanders: string[] = [
  "Kraum, Ludevic's Opus / Tymna the Weaver",
  "Kinnan, Bonder Prodigy",
  "Najeela, the Blade-Blossom",
  "Tivit, Seller of Secrets",
  "Sisay, Weatherlight Captain",
  "Rograkh, Son of Rohgahh / Silas Renn, Seeker Adept",
  "Atraxa, Grand Unifier",
  "Kenrith, the Returned King",
  "Bruse Tarl, Boorish Herder / Thrasios, Triton Hero",
  "Kraum, Ludevic's Opus / Tevesh Szat, Doom of Fools",
  "Dargo, the Shipwrecker / Thrasios, Triton Hero",
  "Yuriko, the Tiger's Shadow",
  "Tayam, Luminous Enigma",
  "Malcolm, Keen-Eyed Navigator / Tymna the Weaver",
  "Malcolm, Keen-Eyed Navigator / Tana, the Bloodsower",
  "Rocco, Cabaretti Caterer",
  "Niv-Mizzet, Parun",
  "Tana, the Bloodsower / Tymna the Weaver",
  "Dihada, Binder of Wills",
  "Ob Nixilis, Captive Kingpin",
  "Thrasios, Triton Hero / Tymna the Weaver",
  "Talion, the Kindly Lord",
  "Jeska, Thrice Reborn / Tymna the Weaver",
  "Magda, Brazen Outlaw",
  "Korvold, Fae-Cursed King",
  "Inalla, Archmage Ritualist",
  "Rograkh, Son of Rohgahh / Thrasios, Triton Hero",
  "Thrasios, Triton Hero / Vial Smasher the Fierce",
  "Krark, the Thumbless / Sakashima of a Thousand Faces",
  "Jhoira, Weatherlight Captain",
  "K'rrik, Son of Yawgmoth",
  "Ikra Shidiqi, the Usurper / Kraum, Ludevic's Opus",
  "Shorikai, Genesis Engine",
  "Malcolm, Keen-Eyed Navigator / Vial Smasher the Fierce",
  "Winota, Joiner of Forces",
  "Bjorna, Nightfall Alchemist / Wernog, Rider's Chaplain",
  "Varragoth, Bloodsky Sire",
  "Rograkh, Son of Rohgahh / Tevesh Szat, Doom of Fools",
  "Breya, Etherium Shaper",
  "Animar, Soul of Elements",
  "Liberator, Urza's Battlethopter",
  "Elsha of the Infinite",
  "Kediss, Emberclaw Familiar / Malcolm, Keen-Eyed Navigator",
  "Slicer, Hired Muscle // Slicer, High-Speed Antagonist",
  "Tevesh Szat, Doom of Fools / Thrasios, Triton Hero",
  "Halana, Kessig Ranger / Tymna the Weaver",
  "Urza, Lord High Artificer",
  "Dargo, the Shipwrecker / Tymna the Weaver",
  "Akiri, Line-Slinger / Thrasios, Triton Hero",
  "Esika, God of the Tree // The Prismatic Bridge",
  "Shalai and Hallar",
  "Jenson Carthalion, Druid Exile",
  "Heliod, the Radiant Dawn // Heliod, the Warped Eclipse",
  "Yeva, Nature's Herald",
  "Haldan, Avid Arcanist / Pako, Arcane Retriever",
  "Zur the Enchanter",
  "Kaalia of the Vast",
  "Narset, Enlightened Exile",
  "Florian, Voldaren Scion",
  "Tasigur, the Golden Fang",
  "Saffi Eriksdotter",
  "The Gitrog Monster",
  "Thada Adel, Acquisitor",
  "Thrasios, Triton Hero / Yoshimaru, Ever Faithful",
  "Teferi, Temporal Archmage",
  "Kess, Dissident Mage",
  "Cormela, Glamour Thief",
  "Kodama of the East Tree / Sakashima of a Thousand Faces",
  "Ghyrson Starn, Kelermorph",
  "Godo, Bandit Warlord",
  "Heliod, Sun-Crowned",
  "Marneus Calgar",
  "Derevi, Empyrial Tactician",
  "Krark, the Thumbless / Thrasios, Triton Hero",
  "Kodama of the East Tree / Tymna the Weaver",
  "Oskar, Rubbish Reclaimer",
  "Jeska, Thrice Reborn / Thrasios, Triton Hero",
  "Krark, the Thumbless / Silas Renn, Seeker Adept",
  "Aesi, Tyrant of Gyre Strait",
  "Daretti, Scrap Savant",
  "Ellivere of the Wild Court",
  "Narset, Enlightened Master",
  "Azami, Lady of Scrolls",
  "Captain Sisay",
  "Armix, Filigree Thrasher / Kraum, Ludevic's Opus",
  "Dargo, the Shipwrecker / Ikra Shidiqi, the Usurper",
  "Toxrill, the Corrosive",
  "Kodama of the East Tree / Tevesh Szat, Doom of Fools",
  "Marath, Will of the Wild",
  "Kroxa, Titan of Death's Hunger",
  "Tatyova, Benthic Druid",
  "Rashmi, Eternities Crafter",
  "Nymris, Oona's Trickster",
  "Solphim, Mayhem Dominus",
  "Kraum, Ludevic's Opus / Reyhan, Last of the Abzan",
  "Minsc, Beloved Ranger",
  "Cazur, Ruthless Stalker / Ukkima, Stalking Shadow",
  "Rograkh, Son of Rohgahh / Tymna the Weaver",
  "Prosper, Tome-Bound",
  "Yisan, the Wanderer Bard",
  "Raffine, Scheming Seer",
  "Rionya, Fire Dancer",
  "Ishai, Ojutai Dragonspeaker / Jeska, Thrice Reborn",
  "Cecily, Haunted Mage / Sophina, Spearsage Deserter",
  "Vadrik, Astral Archmage",
  "Jetmir, Nexus of Revels",
  "Malcolm, Keen-Eyed Navigator / Rograkh, Son of Rohgahh",
  "Sythis, Harvest's Hand",
  "Akiri, Line-Slinger",
  "Rielle, the Everwise",
  "Edric, Spymaster of Trest",
  "Codie, Vociferous Codex",
  "Braids, Arisen Nightmare",
  "Abaddon the Despoiler",
  "Sefris of the Hidden Ways",
  "The First Sliver",
  "Zirda, the Dawnwaker",
  "Jhoira, Ageless Innovator",
  "Etali, Primal Conqueror // Etali, Primal Sickness",
  "Gyruda, Doom of Depths",
  "Kraum, Ludevic's Opus / Thrasios, Triton Hero",
  "Nezahal, Primal Tide",
  "Dina, Soul Steeper",
  "Hurkyl, Master Wizard",
  "Erinis, Gloom Stalker / Street Urchin",
  "Scion of the Ur-Dragon",
  "Moira and Teshar",
  "Sauron, the Dark Lord",
  "Nissa, Resurgent Animist",
  "Zhulodok, Void Gorger",
  "Grand Arbiter Augustin IV",
  "Prossh, Skyraider of Kher",
  "Anhelo, the Painter",
  "Arcum Dagsson",
  "Emry, Lurker of the Loch",
  "Francisco, Fowl Marauder / Thrasios, Triton Hero",
  "Ishai, Ojutai Dragonspeaker / Kediss, Emberclaw Familiar",
  "Miara, Thorn of the Glade / Thrasios, Triton Hero",
  "Kodama of the East Tree / Kraum, Ludevic's Opus",
  "Elmar, Ulvenwald Informant / Wernog, Rider's Chaplain",
  "Atla Palani, Nest Tender",
  "Go-Shintai of Life's Origin",
  "Miirym, Sentinel Wyrm",
  "Baral, Chief of Compliance",
  "Sidar Kondo of Jamuraa / Tymna the Weaver",
  "Jan Jansen, Chaos Crafter",
  "Greymond, Avacyn's Stalwart",
  "Jeska, Thrice Reborn / Kraum, Ludevic's Opus",
  "The Locust God",
  "Momir Vig, Simic Visionary",
  "Xyris, the Writhing Storm",
  "Sheoldred, the Apocalypse",
  "Ardenn, Intrepid Archaeologist / Kraum, Ludevic's Opus",
  "Falthis, Shadowcat Familiar / Jeska, Thrice Reborn",
  "Brallin, Skyshark Rider / Shabraz, the Skyshark",
  "Eruth, Tormented Prophet",
  "Evelyn, the Covetous",
  "Selvala, Heart of the Wilds",
  "Teysa, Orzhov Scion",
  "Blex, Vexing Pest // Search for Blex",
  "Tiamat",
  "Halana, Kessig Ranger / Tevesh Szat, Doom of Fools",
  "Ashaya, Soul of the Wild",
  "Jorn, God of Winter // Kaldring, the Rimestaff",
  "Magus Lucea Kane",
  "Marwyn, the Nurturer",
  "Oswald Fiddlebender",
  "Anje Falkenrath",
  "Vega, the Watcher",
  "Myrel, Shield of Argive",
  "Ardenn, Intrepid Archaeologist / Ishai, Ojutai Dragonspeaker",
  "Noble Heritage / Vhal, Candlekeep Researcher",
  "Breeches, Brazen Plunderer / Malcolm, Keen-Eyed Navigator",
  "Rigo, Streetwise Mentor",
  "Lord Windgrace",
  "Orvar, the All-Form",
  "Satoru Umezawa",
  "Ikra Shidiqi, the Usurper / Tymna the Weaver",
  "Toluz, Clever Conductor",
  "Hapatra, Vizier of Poisons",
  "Loran of the Third Path",
  "Yennett, Cryptic Sovereign",
  "Ivy, Gleeful Spellthief",
  "Minsc & Boo, Timeless Heroes",
  "Old Stickfingers",
  "Koll, the Forgemaster",
  "Urza, Lord Protector",
  "Ramirez DePietro, Pillager",
  "Thalia and The Gitrog Monster",
  "Neera, Wild Mage",
  "Kykar, Wind's Fury",
  "Birgi, God of Storytelling // Harnfel, Horn of Bounty",
  "Rakdos, Lord of Riots",
  "Tadeas, Juniper Ascendant",
  "Sakashima of a Thousand Faces / Tevesh Szat, Doom of Fools",
  "Jaxis, the Troublemaker",
  "Ishai, Ojutai Dragonspeaker / Tevesh Szat, Doom of Fools",
  "Garth One-Eye",
  "Vishgraz, the Doomhive",
  "Yidris, Maelstrom Wielder",
  "Siona, Captain of the Pyleas",
  "Tana, the Bloodsower / Tevesh Szat, Doom of Fools",
  "Mishra, Eminent One",
  "Galazeth Prismari",
  "Yedora, Grave Gardener",
  "Tameshi, Reality Architect",
  "Tevesh Szat, Doom of Fools / Tymna the Weaver",
  "Gale, Waterdeep Prodigy / Scion of Halaster",
  "Dargo, the Shipwrecker / Tevesh Szat, Doom of Fools",
  "Armix, Filigree Thrasher / Thrasios, Triton Hero",
  "Lonis, Cryptozoologist",
  "Emiel the Blessed",
  "Elminster",
  "Grolnok, the Omnivore",
  "Bruse Tarl, Boorish Herder / Malcolm, Keen-Eyed Navigator",
  "Hinata, Dawn-Crowned",
  "Lazav, the Multifarious",
  "Yasharn, Implacable Earth",
  "Valki, God of Lies // Tibalt, Cosmic Impostor",
  "Kraum, Ludevic's Opus / Malcolm, Keen-Eyed Navigator",
  "Tazri, Beacon of Unity",
  "Drana and Linvala",
  "Meria, Scholar of Antiquity",
  "Kroxa and Kunoros",
  "Dargo, the Shipwrecker / Sidar Kondo of Jamuraa",
  "Vaevictis Asmadi, the Dire",
  "Kodama of the West Tree",
  "Rafiq of the Many",
  "Jodah, Archmage Eternal",
  "Gishath, Sun",
  "Jeska, Thrice Reborn",
  "Atraxa, Praetors' Voice",
  "Wilhelt, the Rotcleaver",
  "Teysa Karlov",
  "Krenko, Tin Street Kingpin",
  "Veyran, Voice of Duality",
  "Harald, King of Skemfar",
  "Zaffai, Thunder Conductor",
  "Preston, the Vanisher",
  "Aurelia, the Warleader",
  "Omnath, Locus of Creation",
  "Magar of the Magic Strings",
  "Slimefoot and Squee",
  "Borborygmos and Fblthp",
  "Zimone and Dina",
  "Omnath, Locus of All",
  "Rona, Herald of Invasion // Rona, Tolarian Obliterator",
  "Chulane, Teller of Tales",
  "Bruvac the Grandiloquent",
  "Tymna the Weaver / Yoshimaru, Ever Faithful",
  "Karn, Silver Golem",
  "Meren of Clan Nel Toth",
  "Mayael the Anima",
  "Chatterfang, Squirrel General",
  "Jace, Vryn's Prodigy // Jace, Telepath Unbound",
  "Hans Eriksson",
  "Zabaz, the Glimmerwasp",
  "Selvala, Explorer Returned",
  "Varina, Lich Queen",
  "Mizzix of the Izmagnus",
  "Grazilaxx, Illithid Scholar",
  "Ardenn, Intrepid Archaeologist / Silas Renn, Seeker Adept",
  "Brago, King Eternal",
  "Ikra Shidiqi, the Usurper / Rograkh, Son of Rohgahh",
  "Baral and Kari Zev",
  "Ikra Shidiqi, the Usurper / Ishai, Ojutai Dragonspeaker",
  "Denry Klin, Editor in Chief",
  "Ishai, Ojutai Dragonspeaker / Thrasios, Triton Hero",
  "Folk Hero / Volo, Itinerant Scholar",
  "Yawgmoth, Thran Physician",
  "Thrasios, Triton Hero / Toggo, Goblin Weaponsmith",
  "Bruse Tarl, Boorish Herder / Ikra Shidiqi, the Usurper",
  "Taigam, Ojutai Master",
  "Elesh Norn, Mother of Machines",
  "Aragorn, the Uniter",
  "Bruse Tarl, Boorish Herder / Kodama of the East Tree",
  "Daryl, Hunter of Walkers",
  "Sakashima of a Thousand Faces / Tymna the Weaver",
  "Lurrus of the Dream-Den",
  "Queza, Augur of Agonies",
  "Teshar, Ancestor's Apostle",
  "Oloro, Ageless Ascetic",
  "Rograkh, Son of Rohgahh / Yoshimaru, Ever Faithful",
  "Ao, the Dawn Sky",
  "Obeka, Brute Chronologist",
  "Krark, the Thumbless / Tymna the Weaver",
  "Gaddock Teeg",
  "Saruman, the White Hand",
  "Lavinia, Azorius Renegade",
  "Jodah, the Unifier",
  "Giada, Font of Hope",
  "The Mimeoplasm",
  "Tazri, Stalwart Survivor",
  "Samwise Gamgee",
  "Vohar, Vodalian Desecrator",
  "Heartless Hidetsugu",
  "Extus, Oriq Overlord // Awaken the Blood Avatar",
  "Sen Triplets",
  "Belbe, Corrupted Observer",
  "Maelstrom Wanderer",
  "Elesh Norn, Grand Cenobite",
  "Niv-Mizzet Reborn",
  "Ardenn, Intrepid Archaeologist / Tana, the Bloodsower",
  "Prime Speaker Vannifar",
  "Mishra, Tamer of Mak Fawa",
  "Ravos, Soultender / Tymna the Weaver",
  "Kalamax, the Stormsire",
  "Ratadrabik of Urborg",
  "Hidetsugu and Kairi",
  "Abdel Adrian, Gorion's Ward / Candlekeep Sage",
  "Jeska, Thrice Reborn / Rograkh, Son of Rohgahh",
  "Nekusar, the Mindrazer",
  "Aminatou, the Fateshifter",
  "Frodo, Adventurous Hobbit / Sam, Loyal Attendant",
  "Hansk, Slayer Zealot",
  "Yusri, Fortune's Flame",
  "Sliver Gravemother",
  "Sydri, Galvanic Genius",
  "Jeska, Thrice Reborn / Malcolm, Keen-Eyed Navigator",
  "Kefnet the Mindful",
  "Rankle, Master of Pranks",
  "Tymna the Weaver",
  "Jeleva, Nephalia's Scourge",
  "Kediss, Emberclaw Familiar / Yoshimaru, Ever Faithful",
  "Ezuri, Renegade Leader",
  "Ezuri, Claw of Progress",
  "Light-Paws, Emperor's Voice",
  "Kraum, Ludevic's Opus / Yoshimaru, Ever Faithful",
  "Jhoira of the Ghitu",
  "Lazav, Dimir Mastermind",
  "Ognis, the Dragon's Lash",
  "Zaxara, the Exemplary",
  "Ovika, Enigma Goliath",
  "Lotho, Corrupt Shirriff",
  "Dargo, the Shipwrecker / Silas Renn, Seeker Adept",
  "Malcolm, Keen-Eyed Navigator / Tevesh Szat, Doom of Fools",
  "Bruse Tarl, Boorish Herder / Tana, the Bloodsower",
  "Alela, Artful Provocateur",
  "Prime Speaker Zegana",
  "Skrelv, Defector Mite",
  "Cecily, Haunted Mage / Wernog, Rider's Chaplain",
  "Rowan, Scion of War",
  "Thrasios, Triton Hero",
  "Lord of the Nazgûl",
  "Grist, the Hunger Tide",
  "Kira, Great Glass-Spinner",
  "Purphoros, God of the Forge",
  "Sharuum the Hegemon",
  "Orcus, Prince of Undeath",
  "Adeline, Resplendent Cathar",
  "The Ur-Dragon",
  "Queen Marchesa",
  "Yarok, the Desecrated",
  "Dargo, the Shipwrecker / Jeska, Thrice Reborn",
  "Gandalf the White",
  "Kozilek, the Great Distortion",
  "Trazyn the Infinite",
  "Asmoranomardicadaistinaculdacar",
  "Sidisi, Brood Tyrant",
  "Circu, Dimir Lobotomist",
  "Angus Mackenzie",
  "Osgir, the Reconstructor",
  "Liesa, Shroud of Dusk",
  "Kodama of the East Tree / Thrasios, Triton Hero",
  "Acererak the Archlich",
  "Padeem, Consul of Innovation",
  "Naru Meha, Master Wizard",
  "Wort, Boggart Auntie",
  "Kentaro, the Smiling Cat",
  "Falco Spara, Pactweaver",
  "Francisco, Fowl Marauder / Malcolm, Keen-Eyed Navigator",
  "Ghave, Guru of Spores",
  "Olivia, Crimson Bride",
  "Kasla, the Broken Halo",
  "Hanna, Ship's Navigator",
  "Agent of the Iron Throne / Zellix, Sanity Flayer",
  "Aragorn, King of Gondor",
  "Akiri, Line-Slinger / Francisco, Fowl Marauder",
  "Henry Wu, InGen Geneticist",
  "Lathril, Blade of the Elves",
  "Okaun, Eye of Chaos / Zndrsplt, Eye of Wisdom",
  "Galadriel, Light of Valinor",
  "Ragavan, Nimble Pilferer",
  "Abdel Adrian, Gorion's Ward / Agent of the Iron Throne",
  "River Song",
  "Nashi, Moon's Legacy",
  "Zada, Hedron Grinder",
  "Malik, Grim Manipulator",
  "Hazezon, Shaper of Sand",
  "Alaundo the Seer",
];

const topFiftyCommanders: string[] = [
  "Kraum, Ludevic's Opus / Tymna the Weaver",
  "Kinnan, Bonder Prodigy",
  "Najeela, the Blade-Blossom",
  "Tivit, Seller of Secrets",
  "Sisay, Weatherlight Captain",
  "Rograkh, Son of Rohgahh / Silas Renn, Seeker Adept",
  "Atraxa, Grand Unifier",
  "Kenrith, the Returned King",
  "Bruse Tarl, Boorish Herder / Thrasios, Triton Hero",
  "Kraum, Ludevic's Opus / Tevesh Szat, Doom of Fools",
  "Dargo, the Shipwrecker / Thrasios, Triton Hero",
  "Yuriko, the Tiger's Shadow",
  "Tayam, Luminous Enigma",
  "Malcolm, Keen-Eyed Navigator / Tymna the Weaver",
  "Malcolm, Keen-Eyed Navigator / Tana, the Bloodsower",
  "Rocco, Cabaretti Caterer",
  "Niv-Mizzet, Parun",
  "Tana, the Bloodsower / Tymna the Weaver",
  "Dihada, Binder of Wills",
  "Ob Nixilis, Captive Kingpin",
  "Thrasios, Triton Hero / Tymna the Weaver",
  "Talion, the Kindly Lord",
  "Jeska, Thrice Reborn / Tymna the Weaver",
  "Magda, Brazen Outlaw",
  "Korvold, Fae-Cursed King",
  "Inalla, Archmage Ritualist",
  "Rograkh, Son of Rohgahh / Thrasios, Triton Hero",
  "Thrasios, Triton Hero / Vial Smasher the Fierce",
  "Krark, the Thumbless / Sakashima of a Thousand Faces",
  "Jhoira, Weatherlight Captain",
  "K'rrik, Son of Yawgmoth",
  "Ikra Shidiqi, the Usurper / Kraum, Ludevic's Opus",
  "Shorikai, Genesis Engine",
  "Malcolm, Keen-Eyed Navigator / Vial Smasher the Fierce",
  "Winota, Joiner of Forces",
  "Bjorna, Nightfall Alchemist / Wernog, Rider's Chaplain",
  "Varragoth, Bloodsky Sire",
  "Rograkh, Son of Rohgahh / Tevesh Szat, Doom of Fools",
  "Breya, Etherium Shaper",
  "Animar, Soul of Elements",
  "Liberator, Urza's Battlethopter",
  "Elsha of the Infinite",
  "Kediss, Emberclaw Familiar / Malcolm, Keen-Eyed Navigator",
  "Slicer, Hired Muscle // Slicer, High-Speed Antagonist",
  "Tevesh Szat, Doom of Fools / Thrasios, Triton Hero",
  "Halana, Kessig Ranger / Tymna the Weaver",
  "Urza, Lord High Artificer",
  "Dargo, the Shipwrecker / Tymna the Weaver",
  "Akiri, Line-Slinger / Thrasios, Triton Hero",
  "Esika, God of the Tree // The Prismatic Bridge",
  "Shalai and Hallar",
];

export { allCommanders, topFiftyCommanders };
