export const mtgCardNames = [
  "Abjure",
  "Abnormal Endurance",
  "Aboleth Spawn",
  "Abolish",
  "Abominable Treefolk",
  "Abomination",
  "Abomination of Gudul",
  "Abomination of Llanowar",
  "Aboroth",
  "Aboshan's Desire",
  "Aboshan, Cephalid Emperor",
  "About Face",
  "Abrade",
  "Abrupt Decay",
  "Absolute Grace",
  "Absolute Law",
  "Absolver Thrull",
  "Absorb",
  "Absorb Energy",
  "Absorb Identity",
  "Absorb Vis",
  "Abstract Iguanart",
  "Abstruse Archaic",
  "Abstruse Interference",
  "Abu Ja'far",
  "Abuelo's Awakening",
  "Abuelo, Ancestral Echo",
  "Abuna Acolyte",
  "Abuna's Chant",
  "Abundance",
  "Abundant Growth",
  "Abundant Harvest",
  "Abundant Maw",
  "Abyssal Gatekeeper",
  "Abyssal Gorestalker",
];
